### ISSUE TITLE
Can't Find "feathers-typescript" on the "npm" registry

### ISSUE THREAD

**Issue by SeunLanLege** [feathersjs/feathers-typescript#4]
### Steps to reproduce

```bash
yarn add --dev feathers-typescript
```

![screenshot from 2017-07-29 15-18-17](https://user-images.githubusercontent.com/16494314/28745501-7aaaa6ba-7471-11e7-9a30-127b82f4180b.png)

**Comment by daffl** [comment]
This repository will very likely not be published to npm.
